# Generated by Django 3.0.8 on 2021-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/videos_images/'),
        ),
    ]
