# Generated by Django 3.0.8 on 2021-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/img/news/')),
            ],
        ),
    ]
