# Generated by Django 3.0.8 on 2021-12-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supporters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsaids',
            name='supporters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supporters.supporters'),
        ),
    ]
