# Generated by Django 3.0.8 on 2021-12-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supporters', '0003_auto_20211220_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsaids',
            name='isnumber',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='financialsaids',
            name='supporters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supporters.supporters'),
        ),
    ]
