# Generated by Django 3.0.8 on 2021-12-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supporters', '0004_auto_20211220_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialsaids',
            name='isnumber',
        ),
        migrations.RemoveField(
            model_name='financialsaids',
            name='price',
        ),
        migrations.AlterField(
            model_name='financialsaids',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='financialsaids',
            name='supporters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supporters.supporters'),
        ),
    ]
