# Generated by Django 3.0.8 on 2021-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonCashAssistance', '0002_noncashassistances_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncashassistances',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
